name = "FileExplorer"
uuid = "edaeb83b-eb46-4343-a784-f8799e8c45af"
authors = ["Marcin Koculak <koculak.marcin@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
